name: Frontend CI

on:

  pull_request:
    branches:
      - '**'

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    # Set defaults so all run steps are in frontend folder
    defaults:
      run:
        working-directory: frontend

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js exact version using setup-node v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.4.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 3️⃣ Install frontend dependencies
      - name: Install dependencies
        run: npm ci

      # 5 Run coverage and enforce 100%
      - name: Check coverage
        run: |
          npm run test:coverage
          npx jest --coverage --coverageThreshold='{
            "global": {
              "branches": 100,
              "functions": 100,
              "lines": 100,
              "statements": 100
            }
          }'

   
